// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1004
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProject1004PackageString = "ef52b9f6-1fdb-48bc-8ec2-2cd219e19567";
        public static Guid guidVSIXProject1004Package = new Guid(guidVSIXProject1004PackageString);

        public const string guidVSIXProject1004PackageCmdSetString = "ffd90517-aa5a-4dec-8f50-1bbdb68a13ae";
        public static Guid guidVSIXProject1004PackageCmdSet = new Guid(guidVSIXProject1004PackageCmdSetString);

        public const string guidImagesString = "6ca2759a-4f3b-4f1d-ab1f-a3ccf0dd1d50";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}